### ISSUE TITLE
[Fabric] Serverside crash with pick block on 1.16.5

### ISSUE THREAD

**Issue by Cynosphere** [exaskye/NotEnoughCreativity#20]
<pre>
java.lang.NoSuchMethodError: net.minecraft.class_2248.method_9574(Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;)Lnet/minecraft/class_1799;
	at com.unascribed.notenoughcreativity.PickBlockHandler.pickBlock(PickBlockHandler.java:52)
	at com.unascribed.notenoughcreativity.NotEnoughCreativity.pickBlock(NotEnoughCreativity.java:90)
	at com.unascribed.notenoughcreativity.network.MessagePickBlock.handle(MessagePickBlock.java:56)
	at com.unascribed.notenoughcreativity.repackage.com.elytradev.concrete.network.Message.lambda$doHandleServer$0(Message.java:109)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)
	</pre>

**Comment by Cynosphere** [comment]
`Block.getPickStack` is clientside only for whatever reason. `result = new ItemStack(state.getBlock());` works fine but dunno if it'll break anything.

**Comment by csutora** [comment]
I have the same problem. What mods are you using? It might be a mod compatibility issue, I'm not sure.

**Comment by Cynosphere** [comment]
It's not mod compatibility issue, see the second comment I made as well as:
![image](https://user-images.githubusercontent.com/1606710/117857698-48954c00-b24a-11eb-9502-d1cff58ce751.png)
