### ISSUE TITLE
Incompatible with Origins, crash on entering Creative+ or on connection to server

### ISSUE THREAD

**Issue by mccoolaustinm** [exaskye/NotEnoughCreativity#30]
Traced this to Origins and NEC+ running at same time. https://github.com/apace100/origins-fabric

When server starts with both mods enabled, this series of unique logs appear, caused by reach-entity-attributes that is an inclusion of Origins:

```
17.11 13:21:05 [Server] main/WARN @ModifyConstant conflict. Skipping notenoughcreativity.mixins.json:MixinServerPlayNetworkHandler->@ModifyConstant::modifyOnPlayerInteractBlockDistance(D)D with priority 800, already redirected by mixins.reach-entity-attributes.json:ServerPlayNetworkHandlerMixin->@ModifyConstant::getActualReachDistance(D)D with priority 1000
17.11 13:21:05 [Server] main/WARN @ModifyConstant conflict. Skipping notenoughcreativity.mixins.json:MixinServerPlayNetworkHandler->@ModifyConstant::modifyOnPlayerInteractEntityDistance(D)D with priority 800, already redirected by mixins.reach-entity-attributes.json:ServerPlayNetworkHandlerMixin->@ModifyConstant::getActualAttackRange(DLnet/minecraft/class_2824;)D with priority 1000
17.11 13:21:05 [Server] main/WARN @ModifyConstant conflict. Skipping notenoughcreativity.mixins.json:MixinServerPlayNetworkHandler->@ModifyConstant::modifyOnPlayerInteractEntityDistance(D)D with priority 800, already redirected by mixins.reach-entity-attributes.json:ServerPlayNetworkHandlerMixin->@ModifyConstant::getActualAttackRange(DLnet/minecraft/class_2824;)D with priority 1000

...

17.11 13:21:08 [Server] main/WARN @ModifyConstant conflict. Skipping notenoughcreativity.mixins.json:MixinServerPlayerInteractionManager->@ModifyConstant::modifyBlockBreakingDistance(D)D with priority 800, already redirected by mixins.reach-entity-attributes.json:ServerPlayerInteractionManagerMixin->@ModifyConstant::getActualReachDistance(D)D with priority 1000
```

If nothing is in inventory, everything appears to be working. This is how I first tested this mod and ended up loving it (side note: the creative toggleable "abilities" are amazing, I can't live without them now and they should be in vanilla - excellent work!). Once items are added to inventory however, the crash occurs - or alternatively, if items are already in inventory and button to enter Creative+ is clicked. Server is then softlocked, repeatedly crashing until NEC+ is removed. NEC+ can then be re-added without Origins and appears to work fine.

Full crashlog from softlocked server after joining:

```

Description: Exception in server tick loop

java.lang.AbstractMethodError: Receiver class net.minecraft.class_3222 does not define or inherit an implementation of the resolved method 'abstract void method_7635(net.minecraft.class_1703, int, net.minecraft.class_1799)' of interface net.minecraft.class_1712.
	at net.minecraft.class_1703.method_34246(class_1703.java:211)
	at net.minecraft.class_1703.method_7623(class_1703.java:168)
	at net.minecraft.class_1703.method_7596(class_1703.java:131)
	at com.unascribed.notenoughcreativity.NotEnoughCreativity.updateInventory(NotEnoughCreativity.java:77)
	at net.minecraft.class_3222.handler$znk000$onSpawn(class_3222.java:6202)
	at net.minecraft.class_3222.method_34225(class_3222.java)
	at net.minecraft.class_3324.method_14570(class_3324.java:275)
	at net.minecraft.class_3248.method_33800(class_3248.java:129)
	at net.minecraft.class_3248.method_14384(class_3248.java:117)
	at net.minecraft.class_3248.redirect$zki000$handlePlayerJoin(class_3248.java:563)
	at net.minecraft.class_3248.method_18785(class_3248.java:67)
	at net.minecraft.class_2535.method_10754(class_2535.java:234)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 4.19.0-13-amd64
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3569932520 bytes (3404 MiB) / 5511315456 bytes (5256 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 85839.53
	Virtual memory used (MB): 138938.75
	Swap memory total (MB): 21503.99
	Swap memory used (MB): 21466.27
	JVM Flags: 4 total; -Xmx6144M -Xms1024M -XX:ParallelGCThreads=2 -XX:ThreadStackSize=512
	Fabric Mods: 
		alternatecurrent: Alternate Current 0.4.1
		apoli: Apoli 2.0.5
		calio: Calio 1.3.0
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.1.40
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabricloader: Fabric Loader 0.11.7
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		hydrogen: Hydrogen 0.3
		java: OpenJDK 64-Bit Server VM 16
		lithium: Lithium 0.7.5
		minecraft: Minecraft 1.17.1
		notenoughcreativity: Not Enough Creativity 1.3.2
		origins: Origins 1.1.4
		playerabilitylib: Pal 1.3.0
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		starlight: Starlight 1.0.0+fabric.73f6d37
		worldedit: WorldEdit 7.2.7+9f3e795
	Player Count: 1 / 69; [class_3222['bigbabymecha'/27, l='ServerLevel[Continental - 25000]', x=8943.60, y=92.25, z=400.94]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

I would add the issue to Origins too, but their issues page it does not seem to get much interest from the developer - 142 open issues and many without responses.

**Comment by mccoolaustinm** [comment]
Closed this as it turns out the issue I was having was caused by Cloth API.
